### ISSUE TITLE
system hang when run cyphondock

### ISSUE THREAD

**Issue by crazychengmm** [controlscanmdr/cyphondock#79]
HI
I am new in cyphon. 
I set cyphondock up on my kvm virture server(debian 8 16G/6cpu).
The system has hang several times and i found nothing in syslog,kern.log.
I found blew error on my terminor on time.

-----------
![image](https://user-images.githubusercontent.com/23517542/40226038-435013a2-5abd-11e8-9d70-a1aaafcc8490.png)

-----------
than i setted the gc log on es and logstash.

I just wonder that is there anyone has same issue with me?

Thanks

**Comment by fatalglitch** [comment]
We haven't seen any issues reported similar to this before. Are you running cyphondock or did you install cyphon to KVM domains?

If Docker, can you provide which version of Docker you are running?

**Comment by crazychengmm** [comment]
Hi,fatalglitch
Thanks for your reply.
I run this on my kvm virture host which is installed debian.
By the way it was happened on physical machine first,  I thought it might due to machine too old and low performance,then i change it to a good one(performance is higher).
Docker version is -->
aaaa@jessie:~$ docker --version
Docker version 18.03.1-ce, build 9ee9f40
kernel version is -->
aaaa@jessie:~$ uname -a
Linux jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
aaaa@jessie:~$ cat /etc/debian_version 
8.5

Thanks

**Comment by crazychengmm** [comment]
Hi
I found so many error on es docker.
-------------------------
org.elasticsearch.transport.RemoteTransportException: [hdHiWVZ][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [sys_timestamp] in order to sort on
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:262) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:634) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:485) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:257) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:343) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:340) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.5.jar:5.6.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
-------------------
this error got so many times(almost over 6000 times).
Is this the problem?
