### ISSUE TITLE
Issue with GeoIP

### ISSUE THREAD

**Issue by da7oom20** [controlscanmdr/cyphondock#96]
Dears,

Thank you in advance for the incredible work you have done.

I'm facing the issue below 

`Step 7/16 : ENV GEOIPUPDATE_VER     "4.0.6"                                                                              ---> Using cache                                                                                                        ---> d31bd71b53c2                                                                                                      Step 8/16 : ADD ${GEOIP_BASE_URL}/${GEOIP_CNTR_DB}.gz /tmp/ 
ERROR: Service 'geoip' failed to build: ADD failed: failed to GET https://download.db-ip.com/free/dbip-country-lite-2020-04.mmdb.gz with status 404 Not Found: <html>                                                                           <head><title>404 Not Found</title></head>                                                                               <body bgcolor="white">                                                                                                  <center><h1>404 Not Found</h1></center>                                                                                 <hr><center>nginx/1.10.3</center>                                                                                       </body>                                                                                                                 </html>                                                                                                                 One minute... Waiting for services to start...                                                                          Loading configurations                                                                                                  Error: No such container: cyphondock_cyphon_1                                                                           Create a user account for Cyphon                                                                                        sudo docker exec -it cyphondock_cyphon_1 sh -c python manage.py createsuperuser                                         Note: To get Twitter working, don't forget to enable the reservoir!                                                     Note: You will need to add the index pattern on http://ip_addr:5601/ (cyphon-*)`

I investigate it and found that there is no URL like: [https://download.db-ip.com/free/dbip-country-lite-2020-04.mmdb.gz](url).

The right URL is: [https://download.db-ip.com/free/dbip-country-lite-2020-08.mmdb.gz](url).

How can I solve the issue?

**Comment by desaiparv5** [comment]
@tman971 has already solved the issue but his pull request is not being merged: 
for the time being you can replace your
build value of geoip module with the one fixed by @dvtidefan
e.g. replace line 81 in docker-compose.yml with
`build: https://github.com/dvtidefan17/geoip.git`
do this for all files

**Comment by da7oom20** [comment]
Dear desaiparv5,

thank you that worked, now I'm getting this error:

`    ERROR: Command errored out with exit status 1:                                                                           command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2a92mnqa/maxminddb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2a92mnqa/maxminddb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nhu42n8z                                                                      cwd: /tmp/pip-install-2a92mnqa/maxminddb/                                                                          Complete output (5 lines):                                                                                              Traceback (most recent call last):                                                                                        File "<string>", line 1, in <module>                                                                                    File "/tmp/pip-install-2a92mnqa/maxminddb/setup.py", line 12, in <module>                                                 from setuptools import setup, Extension, Feature                                                                    ImportError: cannot import name 'Feature' `

**Comment by da7oom20** [comment]
I tried again and got this error:

`ERROR: Could not find a version that satisfies the requirement Django==1.11.15 (from -r /usr/src/app/requirements.txt (line 18)) (from versions: none)                                                                                          ERROR: No matching distribution found for Django==1.11.15 (from -r /usr/src/app/requirements.txt (line 18)) `
